mrrs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('room', views.room, name='room'),
    url(r'^$', views.mrrs, name='mrrs'),
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mrrs/', include('mrrs.urls')),
]

mrrs/models.py
from django.db import models
from django.utils import timezone


class room_info(models.Model):
    """
    room_infoテーブルのモデル.

    """

    # 会議室ID : INTEGER型
    room_id = models.IntegerField(primary_key=True)
    # 会議室名 : 文字列型30桁
    room_name = models.CharField(max_length=30)
    # 削除フラグ : INTEGER型
    del_flg = models.IntegerField()

    def __str__(self):
        return self.room_name


class room_reservation(models.Model):
    """
    room_reservationテーブルのモデル.

    """

    # id : INTEGER型で、主キー
    id = models.IntegerField(primary_key=True)
    # 会議室ID : INTEGER型
    room_id = models.ForeignKey(room_info, on_delete=models.CASCADE)
    # 利用者 : 文字列型30桁
    user = models.CharField(max_length=30)
    # 開始日時 : DATETIME型
    start_date_time = models.DateTimeField(default=timezone.now)
    # 終了日時 : DATETIME型
    end_date_time = models.DateTimeField(default=timezone.now)
    # 削除フラグ : INTEGER型
    del_flg = models.IntegerField()

mrrs/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models


class reserv_room(forms.Form):
    """
    reserv_roomのフォーム.

    """

    # 予約ID
    reserv_id = forms.CharField(
        label="ID",
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={"class": "reserve_type_text"}),
    )
    # 会議室ID
    room_id = forms.ModelChoiceField(
        models.room_info.objects, label="会議室名", required=True,
    )
    # 利用者
    reserv_name = forms.CharField(
        label="利用者",
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={"class": "reserve_type_text"}),
    )
    # 開始日時
    start_date_time = forms.SplitDateTimeField(label="開始日時", required=True)

    # 終了日時
    end_date_time = forms.SplitDateTimeField(label="終了日時", required=True)

    def clean(self):
        all_clean_data = super().clean()
        start_date_time = all_clean_data["start_date_time"]
        end_date_time = all_clean_data["end_date_time"]

        if start_date_time >= end_date_time:
            raise forms.ValidationError("終了日時は開始日時より後を選択して下さい。")
        return all_clean_data


class reserv_room_info(forms.Form):
    """
    reserv_room_infoのフォーム.

    """

    # 会議室ID
    room_id = forms.CharField(
        label="会議室ID",
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={"class": "reserve_type_text"}),
    )
    # 会議室名
    room_name = forms.CharField(
        label="会議室名",
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={"class": "reserve_type_text"}),
    )

mrrs/views.py
import calendar
import datetime
import dateutil.parser
from dateutil.relativedelta import relativedelta
from django.db.models import Max
from django.shortcuts import render
from .models import room_info, room_reservation
from . import forms


def mrrs(request):
    """
    会議室予約システム画面の関数
    """
    # 月曜日から始まるカレンダー
    cal = calendar.Calendar(0)
    today = datetime.date.today()
    month_days = cal.monthdatescalendar(today.year, today.month)
    yesterday = today - datetime.timedelta(days=1)
    tomorrow = today + datetime.timedelta(days=1)
    first_day = today.replace(day=1)
    month_after = first_day + relativedelta(months=1)
    month_ago = first_day - relativedelta(months=1)

    # リクエストがPOST形式の場合 データーベースに会議室予約システムの情報を登録する.
    if request.method == "POST":
        # 予約ID
        reserv_id = request.POST.get("reserv_id")
        # 会議室ID
        room_id = request.POST.get("room_id")
        # 利用者
        reserv_name = request.POST.get("reserv_name")
        # 開始日時
        start_date_time_date = request.POST.get("start_date_time_0")
        start_date_time_time = request.POST.get("start_date_time_1")
        start_date_time = start_date_time_date + " " + start_date_time_time
        # 終了日時
        end_date_time_date = request.POST.get("end_date_time_0")
        end_date_time_time = request.POST.get("end_date_time_1")
        end_date_time = end_date_time_date + " " + end_date_time_time

        if "登 録" in request.POST.get("action"):
            max_id_dic = room_reservation.objects.all().aggregate(Max("id"))
            reserv_id = max_id_dic["id__max"] + 1
            # リクエストパラメーターをデーターモデルに当て込みます.
            data_object = room_reservation(
                id=reserv_id,
                room_id=room_info.objects.get(room_id=room_id),
                user=reserv_name,
                start_date_time=start_date_time,
                end_date_time=end_date_time,
                del_flg=0,
            )
            # データーを登録する.
            data_object.save()

        if "削 除" in request.POST.get("action"):
            # リクエストパラメーターをデーターモデルに当て込みます.
            data_object = room_reservation(
                id=reserv_id,
                room_id=room_info.objects.get(room_id=room_id),
                user=reserv_name,
                start_date_time=start_date_time,
                end_date_time=end_date_time,
                del_flg=0,
            )
            # データーを削除する.
            data_object.delete()

        if "更 新" in request.POST.get("action"):
            # リクエストパラメーターをデーターモデルに当て込みます.
            data_object = room_reservation(
                id=reserv_id,
                room_id=room_info.objects.get(room_id=room_id),
                user=reserv_name,
                start_date_time=start_date_time,
                end_date_time=end_date_time,
                del_flg=1,
            )
            # データーを更新する.
            data_object.save()
    else:
        get_date = request.GET.get("days")
        if get_date:
            today = dateutil.parser.parse(get_date)
            month_days = cal.monthdatescalendar(today.year, today.month)
            yesterday = today + datetime.timedelta(days=-1)
            tomorrow = today + datetime.timedelta(days=1)

            first_day = today.replace(day=1)
            month_after = first_day + relativedelta(months=1)
            month_ago = first_day - relativedelta(months=1)

    # データーモデルからデーターを取得する.
    room_data = room_info.objects.all()
    reserv_data = room_reservation.objects.filter(
        start_date_time__year=today.year,
        start_date_time__month=today.month,
        start_date_time__day=today.day,
    )

    # フォームオブジェクトを取得する.
    form = forms.reserv_room()

    # テンプレートに渡す値を設定する
    display = {
        "form": form,
        "room_data": room_data,
        "reserv_data": reserv_data,
        "cal_date": today,
        "month_days": month_days,
        "yesterday": yesterday,
        "tomorrow": tomorrow,
        "month_after": month_after,
        "month_ago": month_ago,
    }

    return render(request, "resurv.html", display)


def room(request):

    # リクエストがPOST形式の場合 データーベースに会議室予約システムの情報を登録する.
    if request.method == "POST":
        # 会議室ID
        room_id = request.POST.get("room_id")
        # 利用者
        room_name = request.POST.get("room_name")
        # リクエストパラメーターをデーターモデルに当て込みます.
        data_object = room_info(room_id=room_id, room_name=room_name, del_flg=0,)
        # データーを登録する.
        data_object.save()

    # データーモデルからデーターを取得する.
    room_data = room_info.objects.all()
    # フォームオブジェクトを取得する.
    form = forms.reserv_room_info(request.GET or None)
    display = {
        "form": form,
        "room_data": room_data,
    }

    return render(request, "room.html", display)

templates/resurv.html
{% load static %}
<!DOCTYPE html>
<html>

<head lang="ja">
  <meta charset="utf-8">
  <title>会議室予約システム</title>
  <!-- google fontsを使用するためgoogleからフォントのcssを取得します。-->
  <link href="https://fonts.googleapis.com/css?family=Courgette|Noto+Serif+JP&display=swap" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="{% static 'jquery.datetimepicker.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'jquery.datetimepicker.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'mrrs.css' %}">


  <script type="text/javascript" language="javascript">
    $(function () {
      $('#id_start_date_time_0').attr('autocomplete', 'off');
      $('#id_start_date_time_1').attr('autocomplete', 'off');
      $('#id_end_date_time_0').attr('autocomplete', 'off');
      $('#id_end_date_time_1').attr('autocomplete', 'off');

      $('#id_start_date_time_0').datetimepicker({ timepicker: false, format: 'Y-m-d' });
      $('#id_start_date_time_1').datetimepicker({ datepicker: false, format: 'H:i' });
      $('#id_end_date_time_0').datetimepicker({ timepicker: false, format: 'Y-m-d' });
      $('#id_end_date_time_1').datetimepicker({ datepicker: false, format: 'H:i' });

      $('.js-modal-open').on('click', function () {
        $('.js-modal').fadeIn();
        $('.reserve_list_row-first').css('z-index', 0);
        $('.js-modal-open-update').css('z-index', 0);
        $('#id_reserv_id').val("");
        $('#id_room_id').val("");
        $('#id_reserv_name').val("");
        $('#id_start_date_time_0').val("");
        $('#id_start_date_time_1').val("");
        $('#id_end_date_time_0').val("");
        $('#id_end_date_time_1').val("");
        $('#input_button').css('display', '');
        $('#update_button').css('display', 'none');
        $('#delete_button').css('display', 'none');

        return false;
      });
      $('.js-modal-open-update').on('click', function () {
        $('.js-modal').fadeIn();
        $('.reserve_list_row-first').css('z-index', 0);
        $('.js-modal-open').css('z-index', -1);
        $('.js-modal-open-update').css('z-index', -1);
        $('#id_reserv_id').val($(this).data('id'));
        $('#id_room_id').val($(this).data('room_id'));
        $('#id_reserv_name').val($(this).data('room_user'));
        $('#id_start_date_time_0').val($(this).data('start_date_time_0'));
        $('#id_start_date_time_1').val($(this).data('start_date_time_1'));
        $('#id_end_date_time_0').val($(this).data('end_date_time_0'));
        $('#id_end_date_time_1').val($(this).data('end_date_time_1'));
        $('#input_button').css('display', 'none');
        $('#update_button').css('display', '');
        $('#delete_button').css('display', '');

        return false;
      });
      $('.js-modal-close').on('click', function () {
        $('.js-modal').fadeOut();
        $('.reserve_list_row-first').css('z-index', 1);
        $('.js-modal-open').css('z-index', 1);
        $('.js-modal-open-update').css('z-index', 1);

        return false;
      });
    });
  </script>


</head>

<body>
  <div class="wrapper">
    <!-- wrapper start -->
    <header>
      <h1>Meeting room reservation system</h1>
    </header>
    <article>
      <!-- reserve_wrapper start -->
      <div class="reserve_wrapper">
        <!-- -------------------------------------------------- -->
        <!-- 入力 リスト                                        -->
        <!-- -------------------------------------------------- -->
        <!-- reserve_list start  -->
        <div class="reserve_list-head">
          <p class="calendar-year-month-date">{{cal_date|date:"Y年m月d日"}}</p>
        </div>
        <div class="reserve_list">
          <div class="reserve_list_row reserve_list_row-houre">
            <!-- 24時間の表記 -->
            <div class="reserve_list_row-first"></div>
            {% for houre in ''|center:24 %}
            <span>{{forloop.counter}}</span>
            {% endfor %}
          </div>

          <!-- 縦線の表記 -->
          <div class="reserve_list_row reserve_list_row-lines">
            {% for count in ''|center:24 %}
            <span></span>
            {% endfor %}
          </div>

          <!-- 会議室の内容 -->
          {% for room_info in room_data %}
          <div class="reserve_list_row">
            <div class="reserve_list_row-first">
              <div class="reserve_text">
                <a class="js-modal-open" href="#">
                  {{room_info.room_name}}：ID[{{room_info.room_id}}]
                </a>
              </div>
            </div>
            <ul class="reserve_list_row-bars">
              <!-- 押下時値を渡す -->
              {% for reserv_info in reserv_data %}
              {% if room_info.room_id|slugify  == reserv_info.room_id|slugify  %}

              <li class="js-modal-open-update"
                style="grid-column: {{reserv_info.start_date_time|date:'H'}}/{{reserv_info.end_date_time|date:'H'}}; background-color: #465DAA;"
                data-id={{reserv_info.id}} data-room_id={{reserv_info.room_id.room_id}}
                data-room_user={{reserv_info.user}}
                data-start_date_time_0="{{reserv_info.start_date_time|date:'Y-m-d'}}"
                data-start_date_time_1="{{reserv_info.start_date_time|date:'H:i'}}"
                data-end_date_time_0="{{reserv_info.end_date_time|date:'Y-m-d'}}"
                data-end_date_time_1="{{reserv_info.end_date_time|date:'H:i'}}">
                <span class="user_name">{{reserv_info.user}}</span></li>
              </li>

              {% endif %}
              {% endfor %}
            </ul>
          </div>
          {% endfor %}
        </div>
        <!-- reserve_list end  -->
        <div class="day-pager-paernt">
          <div>
            <a href="{% url 'mrrs' %}?days={{yesterday|date:'Ymd'}}">
              <p>前日</p>
            </a>
          </div>
          <div>
            <a href="{% url 'mrrs' %}?days={{tomorrow|date:'Ymd'}}">
              <p>翌日</p>
            </a>
          </div>
        </div>
      </div>
      <!-- reserve_wrapper end  -->

      <!-- -------------------------------------------------- -->
      <!-- カレンダー                                         -->
      <!-- -------------------------------------------------- -->
      <div id="mini-calendar">
        <div class="calendar-head">
          <p class="calendar-year-month">{{cal_date|date:"Y年m月"}}</p>
        </div>
        <table>
          <thead>
            <tr>
              <th>月</th>
              <th>火</th>
              <th>水</th>
              <th>木</th>
              <th>金</th>
              <th class="calendar-sat">土</th>
              <th class="calendar-sun">日</th>
            </tr>
          </thead>
          <tbody>
            {% for week in month_days %}
            <tr>
              {% for day in week %}
              <td>
                <a href="{% url 'mrrs' %}?days={{day|date:'Ymd'}}">
                  <i class="calendar-day-number">{{day|date:"d"}}</i>
                  <div class="calendar-labels"></div>
                </a>
              </td>
              {% endfor %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="day-pager-paernt">
        <div>
          <a href="{% url 'mrrs' %}?days={{month_ago|date:'Ymd'}}">
            <p>前月</p>
          </a>
        </div>
        <div>
          <a href="{% url 'mrrs' %}?days={{month_after|date:'Ymd'}}">
            <p>翌月</p>
          </a>
        </div>
      </div>
    </article>

    <footer></footer>

  </div>
  <!-- wrapper end   -->

  <!-- 入力フォームと送信ボタンは formタグで囲み postメソッドで送信する -->
  <form action="" method="POST">
    <!--POSTを行う際に必要 -->
    {% csrf_token %}
    <!-- -------------------------------------------------- -->
    <!-- 入力フォーム                                       -->
    <!-- -------------------------------------------------- -->
    <div class="modal js-modal">
      <div class="modal_bg js-modal-close"></div>
      <div class="modal_content">

        <div class="reserve_input">
          <!-- reserve_input start -->
          <!-- 予約ID -->
          {{ form.reserv_id.as_hidden }}

          <!-- 会議室ID -->
          <div class="reserve_input_div">
            {{ form.room_id }}
            <label>{{ form.room_id.label }}</label>
            <span class="focus_line"></span>
          </div>

          <!-- 利用者 -->
          <div class="reserve_input_div">
            {{ form.reserv_name }}
            <label>{{ form.reserv_name.label }}</label>
            <span class="focus_line"></span>
          </div>

          <!-- 開始日時 -->
          <div class="reserve_input_div">
            {{ form.start_date_time }}
            <label>{{ form.start_date_time.label }}</label>
            <span class="focus_line"></span>
          </div>

          <!-- 終了日時 -->
          <div class="reserve_input_div">
            {{ form.end_date_time }}
            <label>{{ form.end_date_time.label }}</label>
            <span class="focus_line"></span>
          </div>

          <!-- ボタン関連 -->
          <div class="reserve_div_button">
            <div id="input_button" class="reserve_input_div_button">
              <input type="submit" class="submit_insert" name="action" value="登 録">
            </div>

            <div id="update_button" class="reserve_input_div_button">
              <input type="submit" class="submit_insert" name="action" value="更 新">
            </div>

            <div id="delete_button" class="reserve_input_div_button">
              <input type="submit" class="submit_insert" name="action" value="削 除">
            </div>
          </div>
        </div><!-- reserve_input end  -->
        <a class="js-modal-close" href="">閉じる</a>
      </div>
      <!--modal_inner-->
    </div>
    <!--modal-->
  </form>
</body>

</html>

templates/room.html
  
<!DOCTYPE html>
<html>
  <head lang="ja">
    <meta charset="utf-8">
    <title>会議室予約システム</title>
  </head>
  <body>
    <h1>会議室予約システム</h1>
    <!-- 入力フォームと送信ボタンは formタグで囲み postメソッドで送信する -->
    <form action="" method="POST">
      <!--POSTを行う際に必要 -->
      {% csrf_token %}
      <div style='margin:0 auto; width:1000px;'>
        <!--会議室ID-->
        <label>{{ form.room_id.label }} {{ form.room_id }}</label><br/>
        <!--利用者-->
        <label>{{ form.room_name.label }} {{ form.room_name }}</label><br/>
        <br />
        <input type="submit" value="送信">

        {% for room in room_data %}
          <ul>
          <!--会議室ID-->
          <li>{{room.room_id}}</li>
          <!--利用者-->
          <li>{{room.room_name}}</li>
        </ul>
        {% endfor %}

        <br/>
        <br/>
      </div>
    </form>
  </body>
</html>